package edu.isu.umls.exception;

/**
 * @author rsaripa
 *
 * UMLSException class is a custom exception handler for UMLS Visualization
 */
@SuppressWarnings("serial")
public class UMLSException extends Exception {

	public UMLSException() {
	}
	/**
	 * @param message Error message 
	 */
	public UMLSException(String message) {
		super(message);
	}
	/**
	 * @param cause Throwable object generated by the exception
	 */
	public UMLSException(Throwable cause){
		super(cause);
	}
	/**
	 * @param message Error message
	 * @param cause Throwable object generated by the exception
	 */
	public UMLSException(String message, Throwable cause){
		super(message, cause);
	}

	/**
	 * @param message Error message
	 * @param cause Throwable object generated by the exception
	 * @param enableSuppression
	 * @param writableStackTrace
	 */

	public UMLSException(String message, Throwable cause, 
                                       boolean enableSuppression, boolean writableStackTrace){
		super(message, cause, enableSuppression, writableStackTrace);
	}
}
